version: 2
jobs:
  build:
    working_directory: ~/horseman.js
    docker:
      - image: node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install -g yarn
      - run: yarn install
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: yarn test
